name: build and publish to Docker Hub

on:
  push:
    # Publish `master` as Docker `latest` image.
    branches:
      - master
      - develop

    # Publish `v1.2.3` tags as releases.
    tags:
      - v*
  schedule:
    # generate the cert every 2 wks
    - cron: '59 23 1,15 * *'

env:
  IMAGE_NAME: image

jobs:
  # Run tests.
  # See also https://docs.docker.com/docker-hub/builds/automated-testing/
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set subdomain
        run: |
          echo "domain='gh-run-$GITHUB_RUN_NUMBER.${{ secrets.TEST_DOMAIN }}'" > .env
      - name: Override subdomain
        if: ${{ github.event_name == 'schedule' }}
        run: |
          echo "domain='*.${{ secrets.TEST_DOMAIN }}'" > .env
      - name: Run tests
        run: |
          echo "dns_digitalocean_token = ${{ secrets.DIGITALOCEAN_TOKEN }}" > .dns-config.ini
          docker-compose -f docker-compose.test.yml up --exit-code-from certbot-dns
          sudo chmod -R a+r certs
      - uses: actions/upload-artifact@v2
        with:
          path: certs

  # Push image to GitHub Packages.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    # Ensure test job passes before pushing image.
    needs: test

    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v2

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into registry
        run: echo "${{ secrets.DOCKER_HUB_TOKEN }}" | docker login -u keithbentrup --password-stdin

      - name: Push image
        run: |
          # Clean up org, repo, & image name
          read -r IMAGE_ORG IMAGE_REPO <<<$(echo ${{ github.repository }} | sed 's/\// /')
          IMAGE_ORG=$(echo $IMAGE_ORG | sed 's/-//g')
          IMAGE_REPO=$(echo $IMAGE_REPO | sed 's/^docker-//')
          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ORG/$IMAGE_REPO | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION
